const TEXT = {
  id: {
    name: "Nama",
    confirmPassword: "Konfirmasi Password",
    signUpLink: "Belum memiliki akun? Registrasi disini",
    loginLink: "Sudah memiliki akun? Login disini",
    register: "Registrasi",
    emptyFormError: "Tolong isi semua masukan!",
    confirmPasswordError: "Password harus sama dengan konfirmasi password!",
    emptyNote: "Tidak ada catatan.",
    searchNote: "Cari catatan...",
    archived: "Arsip",
    unarchived: "Tidak diarsip",
    archive: "Arsip",
    unarchive: "Tidak arsip",
    detail: "Detil",
    createdAt: "Dibuat pada",
    title: "Judul",
    description: "Deskripsi",
    create: "Buat Catatan",
    delete: "Hapus Catatan"
  },
  eng: {
    name: "Name",
    confirmPassword: "Confirm Passowrd",
    signUpLink: "Don't have an account? Sign up",
    loginLink: "Have an account already? Log in",
    createdAt: "Created at",
    register: "Register",
    emptyFormError: "Please fill all the input!",
    confirmPasswordError: "Password must be the same as confirm password!",
    emptyNote: "There is no note.",
    searchNote: "Search notes...",
    archived: "Archived",
    unarchived: "Unarchived",
    archive: "Archive",
    unarchive: "Unarchive",
    detail: "Detail",
    title: "Title",
    description: "Description",
    create: "Create Note",
    delete: "Delete Note"
  },
};

export default TEXT;